### ISSUE TITLE
websocket.receive: Unknown error unpack requires a string argument of length 2

### ISSUE THREAD

**Issue by oneTimePad** [jrief/django-websocket-redis#142]
I am unable to figure out why this error is occurring. I originally had the redis websockets working, until I created a python3 VE in which I received a similar error as above. I found out that this module might not support python3, so I created a python2.7 VE.  Then I received the error above. It has always worked for me with python2.7 before. I couldn't find out online how to fix this. It occurs if I reload the client page. Python is also not saying the line number on which  this error occurs, which makes it hard to identify the error.

**Comment by jrief** [comment]
Does this mean that I shall revert pull request #139 ?
Or isn't this related to #135?

**Comment by nanuxbe** [comment]
@oneTimePad what version are you using 0.4.5 or master or something else?

**Comment by oneTimePad** [comment]
I closed the issue, because I realized I was using the version from pip and not the current version from here.

**Comment by jrief** [comment]
Just one note, when I wrote this, I pilfered the code in ``websocket.py`` from [gevent-websocket](https://bitbucket.org/noppo/gevent-websocket/overview)

In the meantime that project [ran into the same Python3 problems](https://bitbucket.org/noppo/gevent-websocket/issues/54/python-3-support). Instead of reinventing the wheel, it might be a better idea to pilfer their implementation again.

**Comment by nanuxbe** [comment]
@jrief this could be a solution. In any case, I think #143 would probably be a good test in any case. I'll take a look at it later (unless you want to do it) and see if I can remove the "staticfiles hack" from it first.

**Comment by jrief** [comment]
@nanuxbe no, please go ahead
