### ISSUE TITLE
Saving messages to database

### ISSUE THREAD

**Issue by Lordicus** [jrief/django-websocket-redis#269]
I've build chat application, everything works fine. But I want to save those messages and after user reloads the browser they are retrieved from database. Also, where should I proceed save in post function or somewhere else. 
By the way, when I write several messages to the input and then reload it, only last message shown. I don't understand why I receive this strange behavior.

**Comment by 2DKot** [comment]
I save messages to postgres in POST handler just before `redis_publisher.publish_message(redis_message)` and it works fine.

> By the way, when I write several messages to the input and then reload it, only last message shown.

Do you trying to load messages from redis? You shouldn't use redis to persist messages.
Also, you may receive message after reconnecting because of `WS4REDIS_EXPIRE` is not `0`. You should set `WS4REDIS_EXPIRE = 0` to receive only new messages via webscocket.
Use GET request to receive old messages from database.

Sorry for my bad English.

**Comment by Lordicus** [comment]
Thank you very much for your response.

I've overcame that task and now all my messeges are in Postgres DB. Now I
need to implement infinite scrolling for message fetching, but I know
solution w/ Django's built-in paginator and jQuery, this just matter of
time. Now the other problem occurred: after sending some messages by
$.post() method they are shown only after reloading the page.

And I can't write messages in Russian or Kazakh, but I know there is
ws4redis utf8 validator, but first issue is higher by precedence.
